name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Ensure your build script creates the .dist directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          branch: gh-pages
          folder: .dist # Adjust this if your build output is in a different folder
